import { NextResponse } from 'next/server';

// Mock menu data for development
const mockMenuData = {
  id: 'main-menu-v1',
  name: 'Main Navigation Menu',
  version: '1.0.0',
  lastUpdated: new Date().toISOString(),
  groups: [
    {
      id: 'newborn-group',
      label: 'NEWBORN (0-3M)',
      slug: 'newborn',
      description: 'Products for newborns',
      image: 'https://placehold.co/600/FF69B4/FFFFFF.png',
      imageAlt: 'Newborn Products 0-3 Months',
      ageGroup: 'newborn',
      isActive: true,
      sortOrder: 1,
      displayOptions: {
        showInNavbar: true,
        navbarLabel: 'NEWBORN (0-3M)',
        promotionalText: 'Welcome your little miracle',
      },
      sections: [
        {
          id: 'newborn-clothing',
          heading: 'Clothing',
          description: 'Soft and comfortable clothing for newborns',
          sortOrder: 1,
          categories: [
            {
              id: 'newborn-bodysuits',
              name: 'Bodysuits & Onesies',
              slug: 'newborn',
              description: 'Essential bodysuits for everyday wear',
              productCount: 5,
              isActive: true,
              sortOrder: 1,
              featured: true,
              promotionalBadge: 'Essential',
            },
            {
              id: 'newborn-swaddles',
              name: 'Swaddles & Blankets',
              slug: 'newborn-swaddles',
              description: 'Cozy swaddles for peaceful sleep',
              productCount: 3,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
        {
          id: 'newborn-care',
          heading: 'Care Essentials',
          description: 'Everything you need for newborn care',
          sortOrder: 2,
          categories: [
            {
              id: 'bath-essentials',
              name: 'Bath Essentials',
              slug: 'bath',
              description: 'Gentle bath products for babies',
              productCount: 4,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
            {
              id: 'feeding-supplies',
              name: 'Feeding Supplies',
              slug: 'feeding',
              description: 'Safe feeding essentials',
              productCount: 6,
              isActive: true,
              sortOrder: 2,
              featured: true,
              promotionalBadge: 'Popular',
            },
          ],
        },
        {
          id: 'newborn-gear',
          heading: 'Gear & Accessories',
          description: 'Essential gear for newborn safety and comfort',
          sortOrder: 3,
          categories: [
            {
              id: 'safety-gear',
              name: 'Car Seats & Strollers',
              slug: 'safety',
              description: 'Safety equipment for travel',
              productCount: 2,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
          ],
        },
      ],
    },
    {
      id: 'baby-group',
      label: 'BABY (3-12M)',
      slug: 'baby',
      description: 'Products for growing babies',
      image: 'https://placehold.co/600/0000FF/FFFFFF.png',
      imageAlt: 'Baby Products 3-12 Months',
      ageGroup: 'baby',
      isActive: true,
      sortOrder: 2,
      displayOptions: {
        showInNavbar: true,
        navbarLabel: 'BABY (3-12M)',
        promotionalText: 'Growing with your baby',
      },
      sections: [
        {
          id: 'baby-clothing',
          heading: 'Clothing',
          description: 'Stylish and comfortable clothing for active babies',
          sortOrder: 1,
          categories: [
            {
              id: 'baby-rompers',
              name: 'Rompers & Jumpsuits',
              slug: 'baby-rompers',
              description: 'Perfect for active babies',
              productCount: 4,
              isActive: true,
              sortOrder: 1,
              featured: true,
              promotionalBadge: 'Trending',
            },
            {
              id: 'baby-dresses',
              name: 'Dresses & Outfits',
              slug: 'baby-dresses',
              description: 'Adorable dresses for special occasions',
              productCount: 3,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
        {
          id: 'baby-development',
          heading: 'Development',
          description: 'Toys and products for baby development',
          sortOrder: 2,
          categories: [
            {
              id: 'baby-toys',
              name: 'Toys & Play',
              slug: 'toys',
              description: 'Educational and fun toys',
              productCount: 8,
              isActive: true,
              sortOrder: 1,
              featured: true,
              promotionalBadge: 'Best Sellers',
            },
          ],
        },
        {
          id: 'baby-feeding',
          heading: 'Feeding',
          description: 'Safe feeding essentials for growing babies',
          sortOrder: 3,
          categories: [
            {
              id: 'baby-bottles',
              name: 'Bottles & Sippy Cups',
              slug: 'feeding',
              description: 'BPA-free bottles and training cups',
              productCount: 6,
              isActive: true,
              sortOrder: 1,
              featured: true,
              promotionalBadge: 'Essential',
            },
            {
              id: 'baby-bibs',
              name: 'Bibs & Feeding Accessories',
              slug: 'feeding-accessories',
              description: 'Mess-free feeding solutions',
              productCount: 4,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
      ],
    },
    {
      id: 'toddler-group',
      label: 'TODDLER (1-3Y)',
      slug: 'toddler',
      description: 'Products for active toddlers',
      image: 'https://placehold.co/600/FF0000/FFFFFF.png',
      imageAlt: 'Toddler Products 1-3 Years',
      ageGroup: 'toddler',
      isActive: true,
      sortOrder: 3,
      displayOptions: {
        showInNavbar: true,
        navbarLabel: 'TODDLER (1-3Y)',
        promotionalText: 'For your growing explorer',
      },
      sections: [
        {
          id: 'toddler-clothing',
          heading: 'Clothing',
          description: 'Durable clothing for active toddlers',
          sortOrder: 1,
          categories: [
            {
              id: 'toddler-casual',
              name: 'Casual Wear',
              slug: 'toddler-casual',
              description: 'Comfortable everyday clothing',
              productCount: 5,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
            {
              id: 'toddler-party',
              name: 'Party & Formal',
              slug: 'toddler-party',
              description: 'Special occasion outfits',
              productCount: 2,
              isActive: true,
              sortOrder: 2,
              featured: true,
              promotionalBadge: 'Special',
            },
          ],
        },
        {
          id: 'toddler-play',
          heading: 'Play & Learn',
          description: 'Educational toys and learning materials',
          sortOrder: 2,
          categories: [
            {
              id: 'toddler-toys',
              name: 'Educational Toys',
              slug: 'toddler-toys',
              description: 'Learning through play',
              productCount: 6,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
          ],
        },
        {
          id: 'toddler-feeding',
          heading: 'Feeding & Snacks',
          description: 'Independent feeding solutions for toddlers',
          sortOrder: 3,
          categories: [
            {
              id: 'toddler-utensils',
              name: 'Utensils & Plates',
              slug: 'feeding',
              description: 'Self-feeding utensils and dishware',
              productCount: 5,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
            {
              id: 'toddler-snacks',
              name: 'Snack Containers',
              slug: 'snack-containers',
              description: 'Portable snack and lunch solutions',
              productCount: 3,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
      ],
    },
    {
      id: 'toys-group',
      label: 'TOYS & PLAY',
      slug: 'toys',
      description: 'Fun and educational toys for all ages',
      image: 'https://placehold.co/600/00FF00/FFFFFF.png',
      imageAlt: 'Toys & Play',
      ageGroup: 'general',
      isActive: true,
      sortOrder: 4,
      displayOptions: {
        showInNavbar: true,
        navbarLabel: 'TOYS & PLAY',
        promotionalText: 'Play, learn, and grow!',
      },
      sections: [
        {
          id: 'toys-educational',
          heading: 'Educational Toys',
          description: 'STEM, puzzles, and learning games',
          sortOrder: 1,
          categories: [
            {
              id: 'toys-stem',
              name: 'STEM Toys',
              slug: 'stem-toys',
              description: 'Science, tech, engineering, math',
              productCount: 7,
              isActive: true,
              sortOrder: 1,
              featured: true,
              promotionalBadge: 'Popular',
            },
            {
              id: 'toys-puzzles',
              name: 'Puzzles & Games',
              slug: 'puzzles',
              description: 'Brain teasers and fun games',
              productCount: 5,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
        {
          id: 'toys-outdoor',
          heading: 'Outdoor Play',
          description: 'Active fun for all ages',
          sortOrder: 2,
          categories: [
            {
              id: 'toys-bikes',
              name: 'Bikes & Ride-ons',
              slug: 'bikes',
              description: 'Balance bikes, trikes, and more',
              productCount: 3,
              isActive: true,
              sortOrder: 1,
              featured: false,
            },
            {
              id: 'toys-sports',
              name: 'Sports & Games',
              slug: 'sports',
              description: 'Balls, nets, and outdoor games',
              productCount: 4,
              isActive: true,
              sortOrder: 2,
              featured: false,
            },
          ],
        },
      ],
    },
  ],
  globalSettings: {
    maxCategoriesPerSection: 10,
    showProductCounts: true,
    enablePromotionalBadges: true,
  },
};

export async function GET() {
  try {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 100));
    
    return NextResponse.json(mockMenuData);
  } catch (error) {
    console.error('Error fetching menu navigation:', error);
    return NextResponse.json(
      { error: 'Failed to fetch menu navigation' },
      { status: 500 }
    );
  }
} 